name: app1
description: A new Flutter application.


version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

dev_dependencies:
  http: ^0.12.2
  flutter_test:
    sdk: flutter
  maps_launcher: ^1.2.0
  google_maps_flutter: ^1.0.6
  geolocator: ^5.3.1
  local_auth: ^0.6.1+3
  location: ^3.0.0
  flutter_polyline_points: ^0.1.0
  cupertino_icons: ^0.1.3
  shared_preferences: ^0.5.10
  qr_code_scanner: ^0.0.13
  qr_flutter: ^3.1.0
  flutter_spinkit: "^4.1.2"
  permission_handler: ^5.0.1+1
  material_design_icons_flutter: ^4.0.5755
  shimmer: ^1.0.0
#  units: ^0.0.7

flutter:

  uses-material-design: true
  assets:
    - assets/

